### PR TITLE
EBS volume tagging in postinstall

### PR DESCRIPTION
**Pull request by RodneyMarable**
*Issue #, if available:* #862 

*Description of changes:* 
- Modified the default IAM role to permit EC2CreateTags, EC2DescribeTags, and EC2DeleteTags so the user doesn't have to use custom_iam_role or a custom CloudFormation template to apply tags to EBS resources.  

- Updated the documentation to include an example of applying EC2 tags to EBS volumes associated with a pcluster stack as part of the postinstall process.

- Applied some other formatting and phrasing changes to cli/pcluster/cli.py and cloudformation/README.rst for improved readability.

*Notes:*
A better long term fix would be to have Chef perform this tagging as part of "aws-parallelcluster-cookbook/blob/develop/recipes/base_config.rb" or in a separate recipe (tag_ebs_volumes.rb, or something along those lines).  It would also be great if tags defined in the pcluster config file could be applied to all EBS volumes associated with a pcluster stack.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by sean-smith** [comment]
Closing this because we can add tags to EBS volumes without using a post-install script.

In the `AWS::EC2::Volume` resource, there's a [Tags](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-ebs-volume.html#cfn-ec2-ebs-volume-tags) attribute. If we pass the tags from the cli or config (see [tags](https://aws-parallelcluster.readthedocs.io/en/latest/configuration.html#tags)), we can add them in the cloudformation template.

**Comment by extremoburo** [comment]
Hi Sean ,  can you explain it better how to do this from the config file ?

**Comment by sean-smith** [comment]
@extremoburo You can add tags to your config (or via the cli). For example:

```
[cluster mycluster]
...
tags = {"key" : "value", "key2" : "value2"}
```

With the caveat that for ebs-backed instances this does not tag the master root volume, only ebs or raid volumes created by ParallelCluster.

See https://aws-parallelcluster.readthedocs.io/en/latest/configuration.html#tags

**Comment by extremoburo** [comment]
ok thanks , do you think it will be possible to also tag existing volumes attached to the master in future ?

**Comment by sean-smith** [comment]
Volumes attached with `ebs_snapshot_id = snap-xxxxx`?

For now no. Your best bet is to tag them with a post-install script. This PR has the code to do so.

**Pull request closed without merging**
