### PR TITLE
[develop] Add support for Rocky Linux 8

### PR DESCRIPTION
**Pull request by enrico-usai**
### Description of changes
Added new os in:
* Image Builder components
* constants used by pcluster commands
* CloudWatch dashboard builder
* list of OS supported by DCV
* pcluster configure and other unit tests
* system-analyzer.sh
* pc_support json file
* changelog

### Tests
* Fix new_os.yaml template to always use the NEW_OS placeholder
    * This configuration file must be used to test a new OS, so it's useless to execute tests for other OSes.
* TODO: add new os in the develop.yml configuration.

### References
* Related to https://github.com/aws/aws-parallelcluster-cookbook/pull/2324

### CODE REVIEW

**Comment by niallguerin** [comment]
Hi Enrico,
I see a new aws pc 3.7.x was released this week. Is there any issue that is holding off the release of support for rocky-8 based on what's been tested in above branch to date as I don't see it covered in new release yet in the new release.

**Comment by enrico-usai** [comment]
Hi @niallguerin, 

the support of Rocky Linux 8 wasn't scheduled for 3.7.0 release, where we added Ubuntu22 support.

We have to complete internal testing and will evaluate to support it in the future releases of ParallelCluster.
Thanks for asking.

**Comment by panda1100** [comment]
I'm looking forward to the release of this PR. This will be a good test bed for MPI applications that built for EL8 systems.

**Review by himani2411 — APPROVED** [review]

**Comment by panda1100** [comment]
Thank you Enrico-san! @enrico-usai

**Pull request merged**
