### PR TITLE
Show DCV Connect URL

### PR DESCRIPTION
**Pull request by sean-smith**
Signed-off-by: Sean Smith <seaam@amazon.com>

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by PhilipMorrisJones** [comment]
I am using parallel cluster 2.5.0 and the commit above says it is back ported but I canot see it in 2.5.0

The way I am working is that I run plcuster from cloud9. All that works and I can ssh into the cluster. I know want to use NiceDCV and I have modified my config file and NiceDCV starts up and I can connect to it on port 8443but there is no session: just a blue screen. I can run `pcluster dcv connect` and if I look on the cluster I see a session has been created but it does not open a new browser. It looks like the `--show-url` is the option I want. Is there way round this? It seems I need to cerate a session and a authentication token and use those to make a URL.


```
SupportOrg:~/environment $ pcluster version
2.5.0
SupportOrg:~/environment $ pcluster dcv connect --help
usage: pcluster dcv connect [-h] [--key-path KEY_PATH] cluster_name

positional arguments:
  cluster_name          Name of the cluster to connect to

optional arguments:
  -h, --help            show this help message and exit
  --key-path KEY_PATH, -k KEY_PATH
                        Key path of the SSH key to use for the connection
```

**Comment by sean-smith** [comment]
@PhilipMorrisJones Coming very soon!

**Comment by PhilipMorrisJones** [comment]
How soon? Tomorrow is not soon enough.

**Comment by PhilipMorrisJones** [comment]
So cool, thanks guys.

image

**Pull request merged**
