### PR TITLE
Enable AWS Batch in GovCloud regions

### PR DESCRIPTION
**Pull request by demartinofra**
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by tilne** [comment]
Can you make the following changes?
* Remove the commit for enabling DCV in govcloud, since #2103 took care of that
* In the `scheduler_validator` function defined in `validators.py` there's a list of regions that don't support awsbatch. The govcloud regions should be removed from that one.

**Comment by demartinofra** [comment]
> Can you make the following changes?
> 
> * Remove the commit for enabling DCV in govcloud, since #2103 took care of that
> * In the `scheduler_validator` function defined in `validators.py` there's a list of regions that don't support awsbatch. The govcloud regions should be removed from that one.

* Removed DCV commit
* I had already updated the validator. Are you referring to a different one?

**Comment by tilne** [comment]
> * I had already updated the validator. Are you referring to a different one?

No, just slowly losing my ability to read ;).

These changes LGTM. Since you don't have it marked as ready for review are there other changes you were planning on making?

**Comment by demartinofra** [comment]
> > * I had already updated the validator. Are you referring to a different one?
> 
> No, just slowly losing my ability to read ;).
> 
> These changes LGTM. Since you don't have it marked as ready for review are there other changes you were planning on making?

No, I was just not able to finalize testing

**Comment by tilne** [comment]
I'm going to mark this as ready for review and then approve it, since the needed change for the image update has been merged into develop and this patch on top of that change has been tested.

**Review by tilne — APPROVED** [review]

**Pull request merged**
