### PR TITLE
Separate p4d multinics testing into its own test for release.

### PR DESCRIPTION
**Pull request by davprat**
### Description of changes
* Separated p4d multinics test into its own test so that it can be run by itself
* Hard-coded capacity reservation has been added to make multiple-nics integ tests use ODCR when running on pd4 instances.

### Checklist
- [x] Make sure you are pointing to **the right branch** and add a label in the PR title (i.e. **2.x** vs **3.x**)
- [x] Check all commits' messages are clear, describing what and why vs how.
- [x] Make sure **to have added unit tests or integration tests** to cover the new/modified code.
- [x] Check if documentation is impacted by this change.

Please review the [guidelines for contributing](../CONTRIBUTING.md) and [Pull Request Instructions](https://github.com/aws/aws-parallelcluster/wiki/Git-Pull-Request-Instructions).

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by chenwany — COMMENTED** [review]
Can we move separating p4d tests related changes to the develop branch?

**Review by chenwany — COMMENTED** [review]
Can we rename p4d.yaml to p4d-efa.yaml?

**Comment by davprat** [comment]
> Can we move separating p4d tests related changes to the develop branch?

https://github.com/aws/aws-parallelcluster/pull/4654

**Comment by davprat** [comment]
> Can we rename p4d.yaml to p4d-efa.yaml?

Done.

**Pull request merged**
